import type { VNScript, VNStep, SayStep, ThoughtStep, BgStep, ShowStep, HideStep, NarrationStep, PauseStep, TransitionStep } from "@novel2gal/core";

const VALID_POSITIONS = new Set(["left_far", "left", "center", "right", "right_far"]);

/**
 * Map a free-form transition name to a Ren'Py built-in transition.
 * "cut" means an immediate change — expressed by omitting the with clause.
 * Unknown names fall back to fade instead of generating `with <invalid>`.
 */
function mapTransition(name?: string): string | null {
  if (!name) return null;
  const n = name.toLowerCase().trim();
  if (n === "cut") return null;
  if (n === "fade" || n === "dissolve") return n;
  return "fade";
}

/** Convert VNScript steps to Ren'Py script lines */
export function generateScript(scripts: VNScript[]): string {
  const lines: string[] = [];
  lines.push("# Auto-generated by All Novel Can Be Galgame");
  lines.push("# Do not edit manually");
  lines.push("");

  // Collect unique background IDs for image definitions
  const bgIds = new Set<string>();
  for (const script of scripts) {
    for (const step of script.steps) {
      if (step.type === "bg") bgIds.add((step as any).backgroundId);
    }
  }

  // Define background images
  if (bgIds.size > 0) {
    lines.push("# Background image definitions");
    for (const bgId of bgIds) {
      const safeId = sanitizeId(bgId);
      lines.push(`image bg ${safeId} = "images/bg/${safeId}.png"`);
    }
    lines.push("");
  }

  // Pre-compute scene labels with collision dedup — Ren'Py refuses to load a
  // script that defines the same label twice (e.g. sceneIds differing only in
  // case or punctuation collapse to the same sanitized label)
  const usedLabels = new Set<string>();
  const sceneLabels = scripts.map((script, sIdx) => {
    let base = sanitizeId(script.sceneId || `part_${sIdx + 1}`);
    if (!base) base = `part_${sIdx + 1}`;
    let label = base;
    let n = 2;
    while (usedLabels.has(label)) {
      label = `${base}_${n}`;
      n += 1;
    }
    usedLabels.add(label);
    return label;
  });

  lines.push("label start:");
  // Jump to the FIRST actual label — a hardcoded target breaks every export
  // whose sceneId isn't literally "0001"
  if (sceneLabels.length > 0) {
    lines.push(`    jump ${sceneLabels[0]}`);
  } else {
    lines.push("    return");
  }
  lines.push("");

  let lastTransition: string | null = null;
  /** Emit the pending transition as a standalone `with` statement */
  const flushTransitionAsStatement = () => {
    if (lastTransition) {
      lines.push(`    with ${lastTransition}`);
      lastTransition = null;
    }
  };

  // Remember each character's last explicit position so an expression-only
  // re-show doesn't teleport them back to center
  const lastPosition = new Map<string, string>();

  for (let sIdx = 0; sIdx < scripts.length; sIdx++) {
    const script = scripts[sIdx];
    const sceneLabel = sceneLabels[sIdx];
    lines.push(`label ${sceneLabel}:`);
    lines.push(`    # --- Scene: ${script.sceneId} ---`);
    lines.push("");

    for (const step of script.steps) {
      const withClause = lastTransition ? ` with ${lastTransition}` : "";

      switch (step.type) {
        case "bg": {
          const t = lastTransition ?? "fade";
          lastTransition = null;
          lines.push(`    scene bg ${sanitizeId((step as BgStep).backgroundId)} with ${t}`);
          break;
        }

        case "show": {
          const s = step as ShowStep;
          const id = sanitizeId(s.characterId);
          let pos: string | undefined;
          if (s.position && VALID_POSITIONS.has(s.position)) {
            pos = s.position;
            lastPosition.set(id, pos);
          } else {
            pos = lastPosition.get(id);
          }
          const expr = s.expression ? ` ${sanitizeId(s.expression)}` : "";
          const atClause = pos ? ` at ${pos}, character_display` : " at character_display";
          lines.push(`    show ${id}${expr}${atClause} with dissolve`);
          flushTransitionAsStatement();
          break;
        }

        case "hide": {
          lines.push(`    hide ${sanitizeId((step as HideStep).characterId)} with dissolve`);
          flushTransitionAsStatement();
          break;
        }

        case "narration": {
          lastTransition = null;
          const text = escapeRenpyString((step as NarrationStep).text || "");
          lines.push(`    "${text}"${withClause}`);
          break;
        }

        case "say": {
          lastTransition = null;
          const s = step as SayStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          const text = escapeRenpyString(s.text || "");
          lines.push(`    ${char} "${text}"${withClause}`);
          break;
        }

        case "thought": {
          lastTransition = null;
          const s = step as ThoughtStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          const text = escapeRenpyString(s.text || "");
          lines.push(`    ${char} "（${text}）"${withClause}`);
          break;
        }

        case "pause": {
          const ms = (step as PauseStep).durationMs ?? 1000;
          lines.push(`    pause ${ms / 1000}`);
          flushTransitionAsStatement();
          break;
        }

        case "transition": {
          lastTransition = mapTransition((step as TransitionStep).name);
          break;
        }
      }
    }

    // A trailing transition step with nothing after it still applies to the jump
    flushTransitionAsStatement();

    // 场景结束自动衔接下一个 Scene 或返回
    if (sIdx < scripts.length - 1) {
      lines.push(`    jump ${sceneLabels[sIdx + 1]}`);
    } else {
      lines.push(`    return`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Escape text for a Ren'Py double-quoted string literal. Ren'Py say/narration
 * text performs %-interpolation, [] substitution and {} text tags by default,
 * so all of those must be doubled/escaped; \r must not leak into literals.
 */
function escapeRenpyString(str: string): string {
  return str
    .replace(/\r\n?/g, "\n")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/%/g, "%%")
    .replace(/\[/g, "[[")
    .replace(/\{/g, "{{")
    .replace(/\n/g, "\\n");
}

/** Sanitize an ID for use in Ren'Py (no special chars, underscore-separated) */
function sanitizeId(id: string): string {
  return id
    .replace(/[^a-zA-Z0-9_一-鿿]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}
