import type { VNScript, VNStep, SayStep, ThoughtStep, BgStep, ShowStep, HideStep, NarrationStep, PauseStep, TransitionStep } from "@novel2gal/core";
import { normalizeExpression } from "@novel2gal/agents";

const VALID_POSITIONS = new Set(["left_far", "left", "center", "right", "right_far"]);

/**
 * Map a free-form transition name to a Ren'Py built-in transition.
 * "cut" means an immediate change — expressed by omitting the with clause.
 * Unknown names fall back to fade instead of generating `with <invalid>`.
 */
function mapTransition(name?: string): string | null {
  if (!name) return null;
  const n = name.toLowerCase().trim();
  if (n === "cut") return null;
  if (n === "fade" || n === "dissolve") return n;
  return "fade";
}

/** Convert VNScript steps to Ren'Py script lines */
export function generateScript(scripts: VNScript[]): string {
  const lines: string[] = [];
  lines.push("# Auto-generated by All Novel Can Be Galgame");
  lines.push("# Do not edit manually");
  lines.push("");

  // Collect unique background IDs for image definitions
  const bgIds = new Set<string>();
  for (const script of scripts) {
    for (const step of script.steps) {
      if (step.type === "bg") bgIds.add((step as any).backgroundId);
    }
  }

  // Define background images
  if (bgIds.size > 0) {
    lines.push("# Background image definitions");
    for (const bgId of bgIds) {
      const safeId = sanitizeId(bgId);
      lines.push(`image bg ${safeId} = "images/bg/${safeId}.png"`);
    }
    lines.push("");
  }

  // Pre-compute scene labels with collision dedup — Ren'Py refuses to load a
  // script that defines the same label twice (e.g. sceneIds differing only in
  // case or punctuation collapse to the same sanitized label)
  const usedLabels = new Set<string>();
  const sceneLabels = scripts.map((script, sIdx) => {
    let base = sanitizeId(script.sceneId || `part_${sIdx + 1}`);
    if (!base) base = `part_${sIdx + 1}`;
    let label = base;
    let n = 2;
    while (usedLabels.has(label)) {
      label = `${base}_${n}`;
      n += 1;
    }
    usedLabels.add(label);
    return label;
  });

  lines.push("label start:");
  // Jump to the FIRST actual label — a hardcoded target breaks every export
  // whose sceneId isn't literally "0001"
  if (sceneLabels.length > 0) {
    lines.push(`    jump ${sceneLabels[0]}`);
  } else {
    lines.push("    return");
  }
  lines.push("");

  let lastTransition: string | null = null;
  /** Emit the pending transition as a standalone `with` statement */
  const flushTransitionAsStatement = () => {
    if (lastTransition) {
      lines.push(`    with ${lastTransition}`);
      lastTransition = null;
    }
  };

  // Remember each character's last explicit position so an expression-only
  // re-show doesn't teleport them back to center
  const lastPosition = new Map<string, string>();

  for (let sIdx = 0; sIdx < scripts.length; sIdx++) {
    const script = scripts[sIdx];
    const sceneLabel = sceneLabels[sIdx];
    lines.push(`label ${sceneLabel}:`);
    lines.push(`    # --- Scene: ${script.sceneId} ---`);
    lines.push("");

    for (const step of script.steps) {
      const withClause = lastTransition ? ` with ${lastTransition}` : "";

      switch (step.type) {
        case "bg": {
          const t = lastTransition ?? "fade";
          lastTransition = null;
          lines.push(`    scene bg ${sanitizeId((step as BgStep).backgroundId)} with ${t}`);
          break;
        }

        case "show": {
          const s = step as ShowStep;
          const id = sanitizeId(s.characterId);
          let pos: string | undefined;
          if (s.position && VALID_POSITIONS.has(s.position)) {
            pos = s.position;
            lastPosition.set(id, pos);
          } else {
            pos = lastPosition.get(id);
          }
          // M5: normalize the expression tag so `show` matches the image
          // statement tags + manifest file slugs (both normalized). Raw
          // aliases pass through unchanged when unmapped.
          const expr = s.expression ? ` ${sanitizeId(normalizeExpression(s.expression).label)}` : "";
          
          // Build transform chain: position, shot type, emphasis, enter effect
          const transforms: string[] = [];
          if (pos) transforms.push(pos);
          transforms.push("character_display");
          if (s.shotType && s.shotType !== "waist") transforms.push(`shot_${s.shotType}`);
          if (s.emphasis === "focus") transforms.push("sprite_focus");
          else if (s.emphasis === "dim") transforms.push("sprite_dim");

          const withClauseShow = s.enterEffect === "fade_in" ? " with dissolve"
            : s.enterEffect === "slide_in_left" ? " with moveinleft"
            : s.enterEffect === "slide_in_right" ? " with moveinright"
            : " with dissolve";
          const atClause = ` at ${transforms.join(", ")}`;
          lines.push(`    show ${id}${expr}${atClause}${withClauseShow}`);
          flushTransitionAsStatement();
          break;
        }

        case "hide": {
          const h = step as HideStep;
          // Hide steps have no exitEffect field (IR v1.0 frozen), so all
          // exits use the exit_fade_out *transform* (DDLC thide equivalent:
          // easein .25 shrink+sink+fade). It is emitted via `at`, mirroring
          // the show transform chain above — NOT as a `with` clause, because
          // `with` only accepts transitions (dissolve/fade/vpunch), and a
          // bare transform name there is a Ren'Py syntax error.
          lines.push(`    hide ${sanitizeId(h.characterId)} at exit_fade_out`);
          flushTransitionAsStatement();
          break;
        }

        case "scene_description":
        case "narration": {
          lastTransition = null;
          const text = escapeRenpyString((step as any).text || "");
          lines.push(`    "${text}"${withClause}`);
          break;
        }

        case "action": {
          lastTransition = null;
          const s = step as any; // ActionStep
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          const text = escapeRenpyString(s.text || "");
          if (s.characterId) {
            // Can be styled in Ren'Py layer later
            lines.push(`    ${char} "{i}${text}{/i}"${withClause}`);
          } else {
            lines.push(`    "${text}"${withClause}`);
          }
          break;
        }

        case "say": {
          lastTransition = null;
          const s = step as SayStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          const text = escapeRenpyString(s.text || "");
          lines.push(`    ${char} "${text}"${withClause}`);
          break;
        }

        case "thought": {
          lastTransition = null;
          const s = step as ThoughtStep;
          const char = s.characterId ? sanitizeId(s.characterId) : "narrator";
          const text = escapeRenpyString(s.text || "");
          lines.push(`    ${char} "（${text}）"${withClause}`);
          break;
        }

        case "pause": {
          const ms = (step as PauseStep).durationMs ?? 1000;
          lines.push(`    pause ${ms / 1000}`);
          flushTransitionAsStatement();
          break;
        }

        case "transition": {
          const t = step as TransitionStep;
          lastTransition = mapTransition(t.name);
          // Emit camera effect as ATL
          if (t.cameraEffect && t.cameraEffect !== "none") {
            const effectMap: Record<string, string> = {
              shake_heavy: "with vpunch",
              shake_light: "with hpunch",
              zoom_in_slow: "camera at camera_zoom_in_slow",
              zoom_punch: "camera at camera_zoom_punch",
              flash_white: "with Fade(0.1, 0.3, 0.5, color=\"#fff\")",
            };
            if (effectMap[t.cameraEffect]) {
              lines.push(`    ${effectMap[t.cameraEffect]}`);
            }
          }
          break;
        }
      }
    }

    // A trailing transition step with nothing after it still applies to the jump
    flushTransitionAsStatement();

    // 场景结束自动衔接下一个 Scene 或返回
    if (sIdx < scripts.length - 1) {
      lines.push(`    jump ${sceneLabels[sIdx + 1]}`);
    } else {
      lines.push(`    return`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Escape text for a Ren'Py double-quoted string literal. Ren'Py say/narration
 * text performs %-interpolation, [] substitution and {} text tags by default,
 * so all of those must be doubled/escaped; \r must not leak into literals.
 */
function escapeRenpyString(str: string): string {
  return str
    .replace(/\r\n?/g, "\n")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/%/g, "%%")
    .replace(/\[/g, "[[")
    .replace(/\{/g, "{{")
    .replace(/\n/g, "\\n");
}

/** Sanitize an ID for use in Ren'Py (no special chars, underscore-separated) */
function sanitizeId(id: string): string {
  return id
    .replace(/[^a-zA-Z0-9_一-鿿]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}
