/** Embedded Ren'Py template files */

export const GUI_RPY = `# Ren'Py GUI configuration
# Auto-generated by All Novel Can Be Galgame

init python:
    gui.about = "Generated by All Novel Can Be Galgame"

define gui.text_font = "fonts/simhei.ttf"
define gui.name_text_size = 22
define gui.text_size = 22
define gui.label_text_size = 22
define gui.notify_text_size = 18
define gui.title_text_size = 75

define gui.textbox_height = 278
define gui.textbox_yalign = 1.0

define gui.text_xpos = 268
define gui.text_ypos = 75
define gui.text_width = 744
define gui.text_xalign = 0.0

define gui.name_xpos = 360
define gui.name_ypos = 0
define gui.name_xalign = 0.0

define gui.namebox_width = None
define gui.namebox_height = None
define gui.namebox_borders = Borders(5, 5, 5, 5)
define gui.namebox_tile = False

style namebox:
    xpos gui.name_xpos
    xanchor gui.name_xalign
    xsize gui.namebox_width
    ypos gui.name_ypos
    ysize gui.namebox_height
    padding gui.namebox_borders.padding

style say_label:
    font gui.text_font
    size gui.name_text_size
    xalign gui.name_xalign
    yalign 0.5

define gui.choice_button_width = 1185
define gui.choice_button_height = None
define gui.choice_button_tile = False
define gui.choice_button_text_font = "fonts/simhei.ttf"
define gui.choice_button_text_size = 22
define gui.choice_button_text_xalign = 0.5
define gui.choice_button_text_idle_color = "#ffffffcc"
define gui.choice_button_text_hover_color = "#ffffff"

define gui.navigation_xpos = 60
define gui.skip_indicator = True
define gui.about = _("Powered by All Novel Can Be Galgame")

# Character display transform - scale to fit screen
transform character_display:
    xysize (300, 400)

# Five-point character layout transforms
transform left_far:
    xalign 0.12
    yalign 1.0
transform left:
    xalign 0.30
    yalign 1.0
transform center:
    xalign 0.50
    yalign 1.0
transform right:
    xalign 0.70
    yalign 1.0
transform right_far:
    xalign 0.88
    yalign 1.0

# === Shot Type Transforms (景别缩放) ===
transform shot_full_body:
    zoom 0.82
transform shot_thigh:
    zoom 0.90
transform shot_waist:
    zoom 1.00
transform shot_bust:
    zoom 1.20
transform shot_closeup:
    zoom 1.50

# === Emphasis Transforms (说话者聚焦) ===
transform sprite_focus:
    linear 0.3 matrixcolor BrightnessMatrix(0.0)
transform sprite_dim:
    linear 0.3 matrixcolor BrightnessMatrix(-0.3)

# === Camera Effects (镜头动效) ===
transform camera_shake_heavy:
    parallel:
        ease 0.05 xoffset 8
        ease 0.05 xoffset -8
        ease 0.05 xoffset 6
        ease 0.05 xoffset -4
        ease 0.05 xoffset 0
    parallel:
        ease 0.05 yoffset 4
        ease 0.05 yoffset -4
        ease 0.05 yoffset 2
        ease 0.05 yoffset 0

transform camera_shake_light:
    ease 0.08 xoffset 3
    ease 0.08 xoffset -3
    ease 0.08 xoffset 0

transform camera_zoom_in_slow:
    ease 2.0 zoom 1.25 align (0.5, 0.3)

transform camera_zoom_punch:
    ease 0.15 zoom 1.45 align (0.5, 0.3)

# === Enter Effects (入场动画) ===
transform enter_fade_in:
    alpha 0.0
    linear 0.5 alpha 1.0
transform enter_slide_left:
    xoffset -200 alpha 0.0
    ease 0.4 xoffset 0 alpha 1.0
transform enter_slide_right:
    xoffset 200 alpha 0.0
    ease 0.4 xoffset 0 alpha 1.0

# === Exit Effects (退场动画, DDLC thide equivalent) ===
transform exit_fade_out:
    easein 0.25 zoom 0.95 yoffset -20 alpha 0.0
transform exit_slide_out:
    easein 0.25 xoffset 200 alpha 0.0
`;

/** Escape text interpolated into Ren'Py string literals (%/[]/{}/quotes) */
function escapeRenpyText(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/%/g, "%%")
    .replace(/\[/g, "[[")
    .replace(/\{/g, "{{");
}

export const OPTIONS_RPY = (title: string, safeName: string) => `# Game options
# Auto-generated by All Novel Can Be Galgame

define config.name = _("${escapeRenpyText(title)}")
define config.version = "1.0.0"

define gui.about = _("Generated by All Novel Can Be Galgame\\\\nBased on: ${title}")

define build.name = "${safeName}"
define build.directory = True
`;

export const SCREENS_RPY = `# Default screens
# Auto-generated by All Novel Can Be Galgame

screen say(who, what):
    style_prefix "say"
    window:
        id "window"
        if who is not None:
            window:
                id "namebox"
                style "namebox"
                text who id "who"
        text what id "what"
    if not renpy.variant("small"):
        add SideImage() xalign 0.0 yalign 1.0

style window:
    xalign 0.5
    xfill True
    yalign gui.textbox_yalign
    ysize gui.textbox_height

style say_dialogue:
    properties gui.text_properties("dialogue")
    xpos gui.text_xpos
    xsize gui.text_width
    ypos gui.text_ypos
    text_align gui.text_xalign

screen input(prompt):
    style_prefix "input"
    window:
        vbox:
            xanchor gui.text_xalign
            xpos gui.text_xpos
            xsize gui.text_width
            ypos gui.text_ypos
            text prompt style "input_prompt"
            input id "input"

screen choice(items):
    vbox:
        style_prefix "choice"
        for i in items:
            textbutton i.caption action i.action

style choice_vbox:
    xalign 0.5
    ypos 405
    yanchor 0.5
    spacing 45

screen navigation():
    vbox:
        style_prefix "navigation"
        xpos gui.navigation_xpos
        yalign 0.5
        spacing 6
        textbutton _("History") action ShowMenu("history")
        textbutton _("Save") action ShowMenu("save")
        textbutton _("Load") action ShowMenu("load")
        textbutton _("Preferences") action ShowMenu("preferences")
        textbutton _("Skip") action Skip() alternate Skip(fast=True, confirm=True)
        textbutton _("Auto") action Preference("auto-forward", "toggle")
        textbutton _("Q.Save") action QuickSave()
        textbutton _("Q.Load") action QuickLoad()

screen confirm(message, yes_action, no_action):
    modal True
    zorder 200
    style_prefix "confirm"
    # add "gui/overlay/confirm.png"  # never generated — would crash confirm dialogs
    frame:
        vbox:
            xalign .5
            yalign .5
            spacing 30
            label _(message) style "confirm_prompt" xalign 0.5
            hbox:
                xalign .5
                spacing 100
                textbutton _("Yes") action yes_action
                textbutton _("No") action no_action
`;
