import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Replay-parity test (stage-1 acceptance).
 *
 * Compares the committed pristine snapshot (captured from the PRE-refactor
 * monolithic pipeline under a scripted LLM) against the post-refactor
 * snapshot. Key-order differences introduced by zod parsing are canonicalized
 * away (sorted keys); any semantic difference fails.
 *
 * The snapshots are regenerated by:
 *   npx tsx apps/api/src/scripts/capture-parity-baseline.ts --tag after
 * (pristine tag came from a HEAD worktree run — see session log 2026-10-03.)
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const pristine = JSON.parse(fs.readFileSync(path.join(here, "parity-pristine.json"), "utf8"));
const after = JSON.parse(fs.readFileSync(path.join(here, "parity-after.json"), "utf8"));

function sortKeys(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v && typeof v === "object") {
    const r: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>).sort()) r[k] = sortKeys((v as Record<string, unknown>)[k]);
    return r;
  }
  return v;
}

const canon = (v: unknown) => JSON.stringify(sortKeys(v));

describe("stage-1 replay parity (pristine vs stage-function refactor)", () => {
  it("covers the same artifact set", () => {
    expect(Object.keys(after).sort()).toEqual(Object.keys(pristine).sort());
  });

  it.each(Object.keys(pristine))("%s is semantically identical", (key) => {
    expect(canon(after[key])).toBe(canon(pristine[key]));
  });

  it("character profiles (M4 bible lock) survived the refactor", () => {
    const profiles = after["character_profiles.json"] as any;
    expect(profiles).toBeDefined();
    expect(Object.keys(profiles).length).toBeGreaterThan(0);
  });
});
